spring:
  application:
  name: ai-code-helper
  profiles:
    active: local
langchain4j:
  community:
    dashscope:
      chat-model:
        api-key: ${qwen.api-key}
        model-name: ${qwen.model-name}
      embedding-model:
        model-name: ${embedding-model.name}
        api-key: ${embedding-model..api-key}
